# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 981a2632e11ebf99f3164de0c9131a3248b5762e1d337f71972d176376c174b248342ffb980fb3991574f31068821b17209c0faff210ee5f5ef28149da68d529

test:
  secret_key_base: 4ba0ca8efebf0d2d1c382f14652728cd4d6cf283494b859cd0f841613e4aa62936d0ba0c56c84d7fc212546f332042c2b2ce0a7fe9ae02833dc0a428717d70b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
